CREATE TABLE `master_convenios` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Dmssnum` varchar(20) NOT NULL,
  `Dmacct` varchar(20) NOT NULL,
  `Uxmescast` int(5) NOT NULL,
  `Dmcurbal` double(10,2) NOT NULL,
  `Uxtot_adeu` double(10,2) NOT NULL,
  `Dmpayoff` double(10,2) NOT NULL,
  `Uxsdo_vi_v` double(10,2) NOT NULL,
  `Uxcap_cred` double(10,2) NOT NULL,
  `Uxint_cred` double(10,2) NOT NULL,
  `Uxmora_cred` double(10,2) NOT NULL,
  `Uxexig_cre` double(10,2) NOT NULL,
  `Dmamtdlq` double(10,2) NOT NULL,
  `U6pag_min` double(10,2) NOT NULL,
  `U6sdo_cort` double(10,2) NOT NULL,
  `plastico_pago` varchar(20) NOT NULL,
  `Nombre` varchar(100) NOT NULL,
  `Fec_ape` date NOT NULL,
  `Cepa` varchar(10),
  `Modalidad` varchar(10),
  `Macro_gen` varchar(30),
  `Gpo_meta` varchar(30),
  `Spei_num_key` varchar(20),
  `Portafolio` varchar(30),
  `Mto_principal` double(10,2) NOT NULL,
  `Int_ordinario` double(10,2) NOT NULL,
  `Moratorios` double(10,2) NOT NULL,
  `Comp_exigible` double(10,2) NOT NULL,
  `Total_adeudo` double(10,2) NOT NULL,
  `Saldo_contable` double(10,2) NOT NULL,
  `Moneda` int(4) NOT NULL,
  `Cliente` int(5) NOT NULL,
  `Producto` int(5) NOT NULL,
  `Fecha_neg` date NOT NULL,
  `Fecha_emi` date NOT NULL,
  `Quita_max_st` double(6,2) NOT NULL,
  `Quita_max_sc` double(6,2) NOT NULL,
  `Quita_neg` double(6,2) NOT NULL,
  `Total_pago` double(10,2) NOT NULL,
  `Saldo_usado` char(1) NOT NULL,
  `Observaciones` varchar(255) DEFAULT NULL,
  `Estado_conv` int(2) NOT NULL,
  `Folio_pre` varchar(10) NOT NULL,
  `Folio_cons` int(4) NOT NULL,
  `Cancelado` bit(1) NOT NULL,
  `Excepcion` bit(1) NOT NULL,
  `Auto_excep` char(10) NOT NULL,
  `Telefono` varchar(13) NOT NULL,
  `Tipo_tel` varchar(10) NOT NULL,
  `Email` varchar(100) NOT NULL,
  `Etapa` varchar(13) NOT NULL,
  `Restitucion` varchar(15) NOT NULL,
  `Tipo_negoid` int(11) NOT NULL,
  `Tipo_convid` int(11) NOT NULL,
  `Tipo_convid_alt` int(11) NOT NULL,
  `Plataforma` varchar(3) NOT NULL,
  `Periodicidad` varchar(1) NOT NULL,
  `CreatedBy` char(10) NOT NULL,
  `CreatedDate` datetime NOT NULL,
  `UpdatedBy` char(10) NOT NULL,
  `UpdatedDate` datetime NOT NULL,
  `DeletedBy` char(10) NOT NULL,
  `DeletedDate` datetime NOT NULL,
  PRIMARY KEY (`Id`),
  KEY `idx1` (`Dmacct`),
  KEY `idx2` (`Dmssnum`),
  KEY `idx3` (`Fecha_neg`),
  KEY `idx4` (`Nombre`),
  UNIQUE `idx5` (`Folio_pre`,`Folio_cons`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=latin1 COMMENT='Master de convenios';
